apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: userapp
  name: userapp
  namespace: otus
spec:
  replicas: 3
  selector:
    matchLabels:
      app: userapp
  template:
    metadata:
      labels:
        app: userapp
    spec:
      containers:
      - name: userapp
        image: docker.io/widedreadnout/otus-microservice-user
        ports:
          - containerPort: 8000
        volumeMounts:
          - name: secrets
            mountPath: /app/secrets
            readOnly: true
      volumes:
      - name: secrets
        secret:
          secretName: secret-appsettings

---

apiVersion: v1
kind: Service
metadata:
  name: userapp-service
  namespace: otus

spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: userapp
  type: NodePort

---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: userapp-ingress
  namespace: otus
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: "arch.homework"
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: userapp-service
              port:
                number: 80