{
 "title": "Nginx Dashboard By HTTP Methods",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "method",
    "label": "Method",
    "query": {
     "query": "label_values(nginx_ingress_controller_requests,method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(method) (irate(nginx_ingress_controller_requests{method=~\"$method\"}[2m]))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Errors rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "increase(nginx_ingress_controller_requests{method=~\"$method\", status=\"500\"}[$__interval])",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Latency max quantile(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=~\"$method\"}[1m])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Latency 0.99 quantile(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=~\"$method\"}[1m])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Latency 0.95 quantile(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=~\"$method\"}[1m])))",
     "legendFormat": "{{ method }}"
    }
   ]
  },
  {
   "title": "Latency 0.5 quantile(ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le, method) (rate(nginx_ingress_controller_request_duration_seconds_bucket{method=~\"$method\"}[1m])))",
     "legendFormat": "{{ method }}"
    }
   ]
  }
 ]
}